### PR TITLE
Update includemocs.py

### PR DESCRIPTION
**Pull request by nickdademo**
Handle source files which have special characters such as the micron/mu character (for example, in code comments).

### CODE REVIEW

**Comment by nickdademo** [comment]
@dangelog Does KDAB intend to merge fixes from the community or shall I close the PR? :)

**Comment by dangelog** [comment]
Hi,

Thank you for the patch! I don't think I've ever received a notification about it.

LGTM, I assume this is a problem on Windows, where open() would use ANSI by default?

**Comment by nickdademo** [comment]
> Hi,
> 
> Thank you for the patch! I don't think I've ever received a notification about it.
> 
> LGTM, I assume this is a problem on Windows, where open() would use ANSI by default?

That's right! This issue occurs on Windows.

**Comment by winterz** [comment]
I was planning to pylint includemocs.py sometime soon.
pylint would have found this issue.

if anyone else wants to fix the pylint issues for me feel free :)

thanks for the contribution

**Pull request merged**
