### PR TITLE
qAsConst is deprecated, use std::as_const

### PR DESCRIPTION
**Pull request by dfaure-kdab**

### CODE REVIEW

**Review by AndreSomers — COMMENTED** [review]
Looks good to me, but this does mean we're requiring C++17. Is that intentional?

**Comment by dfaure-kdab** [comment]
I couldn't find a KDToolBox-wide CXX_STANDARD requirement, so I don't know what's the current status.
But well who doesn't have C++17 these days?

The bit I do need is UpdateableModel.h, for KDABViewer to build with recent Qt and without deprecation warnings.

**Comment by dantti** [comment]
I guess it needs to add KDTOOLBOX_CXX17 to disable building and likely requiring it when enabled for it to pass CI

**Comment by dfaure-kdab** [comment]
Qt 6 requires C++17 anyway, but I see the point about Qt5.
Can we make KDTOOLBOX_CXX17 default to ON though, and only disable it on old Qt5+old-compiler CI builds?

**Comment by dantti** [comment]
It can be on by default, CI compilers are all new enough, it's just that KDStlContainerAdaptor nor Qt5 requires C++-17.

**Comment by dfaure-kdab** [comment]
Done. I reverted the change to qt/qml/PropertySelector/PropertySelector.cpp because that code isn't built anywhere so I can't test changes there => someone else's problem.

**Comment by dantti** [comment]
LGTM tho on the tests part I think you could've just made the vector const, no?

**Comment by dfaure-kdab** [comment]
ping? who approves KDToolBox merge requests?

**Pull request merged**
